name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt-get -qq install pkg-config libssl-dev protobuf-compiler git

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Check formatting
        run: cargo fmt --all -- --check
